Add unicode to Gemfile
Getting error from CiteProc without unicode

CiteProc requires the `unicode_utils` or `unicode` Gem on Ruby 2.3
bundler: failed to load command: jekyll (/Volumes/dsfe/dsfe/vendor/bundle/ruby/2.3.0/bin/jekyll)
NameError: undefined method `upcase' for module `CiteProc'